#!/bin/bash

################################################################################
# setup-opencode.sh - Configure .opencode/ directory with shared + variant configs
#
# Usage:
#   ./scripts/setup-opencode.sh [variant] [--cwd /path]
#
# Examples:
#   ./scripts/setup-opencode.sh base              # Setup base configs only
#   ./scripts/setup-opencode.sh python            # Setup base + Python overrides
#   ./scripts/setup-opencode.sh python --cwd /tmp # Setup in different directory
#
# Description:
#   This script populates the .opencode/ directory by merging:
#   1. shared-config/ (source of truth for all variants)
#   2. Language-specific variant/ (overrides/extends shared)
#
# Exit Codes:
#   0 = Success
#   1 = Invalid variant
#   2 = Missing directories
#   3 = Setup failed
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REPO_ROOT="${PWD}"
VARIANT="base"
OPENCODE_DIR="${REPO_ROOT}/.opencode"
SHARED_CONFIG_DIR="${REPO_ROOT}/shared-config"

# Argument parsing
while [[ $# -gt 0 ]]; do
  case $1 in
    base|python|cpp|go|rust|javascript|nodejs|java)
      VARIANT="$1"
      shift
      ;;
    --cwd)
      REPO_ROOT="$2"
      OPENCODE_DIR="${REPO_ROOT}/.opencode"
      SHARED_CONFIG_DIR="${REPO_ROOT}/shared-config"
      shift 2
      ;;
    *)
      echo -e "${RED}Error: Unknown option '$1'${NC}"
      echo "Usage: $0 [variant] [--cwd /path]"
      exit 1
      ;;
  esac
done

# Logging functions
log_info() {
  echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
  echo -e "${GREEN}✓${NC} $1"
}

log_error() {
  echo -e "${RED}✗${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}⚠${NC} $1"
}

# Validation
log_info "Validating setup..."

if [[ ! -d "${SHARED_CONFIG_DIR}" ]]; then
  log_error "shared-config/ directory not found at ${SHARED_CONFIG_DIR}"
  exit 2
fi

log_success "shared-config/ found"

if [[ "${VARIANT}" != "base" && ! -d "${REPO_ROOT}/${VARIANT}" ]]; then
  log_error "Variant directory not found: ${REPO_ROOT}/${VARIANT}"
  exit 2
fi

if [[ "${VARIANT}" != "base" ]]; then
  log_success "Variant '${VARIANT}/' found"
fi

# Setup
log_info "Setting up .opencode/ with variant: ${VARIANT}"

# Step 1: Clear existing .opencode/
if [[ -d "${OPENCODE_DIR}" ]]; then
  log_warn "Removing existing ${OPENCODE_DIR}/"
  rm -rf "${OPENCODE_DIR}"
fi

# Step 2: Copy shared-config to .opencode
log_info "Copying shared-config/ to .opencode/..."
cp -r "${SHARED_CONFIG_DIR}" "${OPENCODE_DIR}"
log_success "Copied shared-config/ to .opencode/"

# Step 3: Overlay variant if not base
if [[ "${VARIANT}" != "base" ]]; then
  VARIANT_DIR="${REPO_ROOT}/${VARIANT}"
  log_info "Overlaying ${VARIANT}/ configs..."
  
  # Using rsync to merge variant on top of .opencode (without --delete to preserve shared)
  if command -v rsync &> /dev/null; then
    rsync -av "${VARIANT_DIR}/" "${OPENCODE_DIR}/" || {
      log_error "rsync failed"
      exit 3
    }
  else
    # Fallback to cp if rsync not available
    log_warn "rsync not found, using cp as fallback"
    cp -r "${VARIANT_DIR}"/* "${OPENCODE_DIR}/" 2>/dev/null || true
  fi
  
  log_success "Overlayed ${VARIANT}/ configs onto .opencode/"
fi

# Step 4: Create .gitignore for .opencode (prevent accidental commits)
log_info "Creating .opencode/.gitignore..."
cat > "${OPENCODE_DIR}/.gitignore" << 'EOF'
# This directory is generated by setup-opencode.sh
# Do not edit files in this directory - they will be overwritten
# Edit shared-config/ or variant directories instead

*
!.gitignore
!README.md
EOF
log_success "Created .opencode/.gitignore"

# Step 5: Summary
log_info "Setup complete!"
echo ""
echo -e "${BLUE}Summary:${NC}"
echo "  Variant: ${VARIANT}"
echo "  Location: ${OPENCODE_DIR}"
echo ""

# List what was created
if [[ -d "${OPENCODE_DIR}/agents" ]]; then
  agent_count=$(find "${OPENCODE_DIR}/agents" -name "*.md" -not -name "README.md" | wc -l)
  echo "  Agents: ${agent_count}"
fi

if [[ -d "${OPENCODE_DIR}/commands" ]]; then
  command_count=$(find "${OPENCODE_DIR}/commands" -name "*.md" -not -name "README.md" | wc -l)
  echo "  Commands: ${command_count}"
fi

echo ""
log_success "Ready to use! .opencode/ is now populated."
echo ""
echo -e "${YELLOW}Note:${NC} Do not edit .opencode/ directly. Changes will be lost when running this script."
echo "Edit shared-config/ or ${VARIANT}/ instead, then run: $0 ${VARIANT}"

exit 0
